// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MovieID struct {
	ID            int32          `db:"id" json:"id"`
	OriginalTitle string         `db:"original_title" json:"original_title"`
	Adult         bool           `db:"adult" json:"adult"`
	Video         bool           `db:"video" json:"video"`
	Popularity    pgtype.Numeric `db:"popularity" json:"popularity"`
}
