// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MovieID struct {
	ID            int32          `db:"id" json:"id"`
	OriginalTitle string         `db:"original_title" json:"original_title"`
	Adult         bool           `db:"adult" json:"adult"`
	Video         bool           `db:"video" json:"video"`
	Popularity    pgtype.Numeric `db:"popularity" json:"popularity"`
}

type MovieLog struct {
	ID           int64              `db:"id" json:"id"`
	UserID       int64              `db:"user_id" json:"user_id"`
	MovieID      int32              `db:"movie_id" json:"movie_id"`
	WatchedOn    pgtype.Date        `db:"watched_on" json:"watched_on"`
	Note         pgtype.Text        `db:"note" json:"note"`
	RankPosition pgtype.Int4        `db:"rank_position" json:"rank_position"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID          int64              `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	Bio         pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
