// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchMovies = `-- name: SearchMovies :many
SELECT id, original_title, adult, video, popularity,
       similarity(original_title, $1) AS score
FROM movie_ids
WHERE similarity(original_title, $1) > 0.1
ORDER BY score DESC, popularity DESC
LIMIT 20
`

type SearchMoviesRow struct {
	ID            int32          `db:"id" json:"id"`
	OriginalTitle string         `db:"original_title" json:"original_title"`
	Adult         bool           `db:"adult" json:"adult"`
	Video         bool           `db:"video" json:"video"`
	Popularity    pgtype.Numeric `db:"popularity" json:"popularity"`
	Score         float32        `db:"score" json:"score"`
}

func (q *Queries) SearchMovies(ctx context.Context, query string) ([]SearchMoviesRow, error) {
	rows, err := q.db.Query(ctx, searchMovies, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMoviesRow
	for rows.Next() {
		var i SearchMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalTitle,
			&i.Adult,
			&i.Video,
			&i.Popularity,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
