// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, username string) (User, error)
	DeleteUser(ctx context.Context, id int64) (int64, error)
	ListUsers(ctx context.Context) ([]User, error)
	SearchMovies(ctx context.Context, query string) ([]SearchMoviesRow, error)
}

var _ Querier = (*Queries)(nil)
