// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	SearchMovies(ctx context.Context, query string) ([]SearchMoviesRow, error)
}

var _ Querier = (*Queries)(nil)
